name: ovigestao
description: "Aplicativo de gerenciamento de rebanho da Fazenda Baixinha."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  flutter_localizations:
    sdk: flutter
  uuid: ^4.6.0
  image_picker: ^1.2.3
  image_cropper: ^12.2.1
  supabase_flutter: ^2.17.2
  connectivity_plus: ^7.0.0
  flutter_launcher_icons: ^0.14.4
  share_plus: ^13.3.0
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  fl_chart: ^1.1.1
  flutter_local_notifications: ^22.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ovigestao_logo.png
    - assets/images/ovigestao_icon.png
    - assets/images/icon_administracao.png
    - assets/images/icon_agenda.png
    - assets/images/icon_animais.png
    - assets/images/icon_cobertura.png
    - assets/images/icon_configuracoes.png
    - assets/images/icon_cordeiro.png
    - assets/images/icon_estoque.png
    - assets/images/icon_farmacia.png
    - assets/images/icon_financeiro.png
    - assets/images/icon_manejo.png
    - assets/images/icon_nascimento.png
    - assets/images/icon_ovino_femea.png
    - assets/images/icon_ovino_macho.png
    - assets/images/icon_relatorios.png
    - assets/images/icon_reproducao.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/ovigestao_icon.png"
  min_sdk_android: 21
