name: ovigestao
description: "Aplicativo de gerenciamento de rebanho da Fazenda Baixinha."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  flutter_localizations:
    sdk: flutter
  uuid: ^4.6.0
  image_picker: ^1.2.3
  image_cropper: ^12.2.1
  supabase_flutter: ^2.17.2
  connectivity_plus: ^7.0.0
  flutter_launcher_icons: ^0.14.4
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ovigestao_logo.png
    - assets/images/ovigestao_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/ovigestao_icon.png"
  min_sdk_android: 21
