// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvoZs9uSxhvSDUCGPUAikLNZ1uVm4s0dY',
    appId: '1:237608748518:web:55932ba618118038b04227',
    messagingSenderId: '237608748518',
    projectId: 'ovigestao',
    authDomain: 'ovigestao.firebaseapp.com',
    storageBucket: 'ovigestao.firebasestorage.app',
    measurementId: 'G-VE52EWJ4QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADIsDPJBIaTxVj-RdtXhqJWQGxpQw1qZM',
    appId: '1:237608748518:android:e4bd8ad47777981cb04227',
    messagingSenderId: '237608748518',
    projectId: 'ovigestao',
    storageBucket: 'ovigestao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARLGIoUvFgsVOGYinU-FjCiW4hSKzEU20',
    appId: '1:237608748518:ios:0e6cf00b0de6d925b04227',
    messagingSenderId: '237608748518',
    projectId: 'ovigestao',
    storageBucket: 'ovigestao.firebasestorage.app',
    iosBundleId: 'com.example.rebanhoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARLGIoUvFgsVOGYinU-FjCiW4hSKzEU20',
    appId: '1:237608748518:ios:0e6cf00b0de6d925b04227',
    messagingSenderId: '237608748518',
    projectId: 'ovigestao',
    storageBucket: 'ovigestao.firebasestorage.app',
    iosBundleId: 'com.example.rebanhoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvoZs9uSxhvSDUCGPUAikLNZ1uVm4s0dY',
    appId: '1:237608748518:web:03442175e1867b32b04227',
    messagingSenderId: '237608748518',
    projectId: 'ovigestao',
    authDomain: 'ovigestao.firebaseapp.com',
    storageBucket: 'ovigestao.firebasestorage.app',
    measurementId: 'G-HLRES2MHRW',
  );
}
